name: Veracode Static Pipeline Scanner

on:
  workflow_call:
    inputs:
      policy_name:
        required: true
        type: string

  
jobs:
  pipeline_scan:
    runs-on: ubuntu-latest
    name: pipeline scan

    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      
      # get the compiled binary from a previous job
      - name: get archive
        uses: actions/download-artifact@v3
        with:
          name: veracode-artifact
          path: ./veracode_artifact_directory
      
      - name: Get the name of the downloaded files
        run: |
          artifact_file=$(ls -1 ./veracode_artifact_directory | head -n 1)
          echo "veracode_artifact=$artifact_file" >> $GITHUB_ENV

      # run the pipeline scan action
      - name: Veracode Pipeline-Scan
        id: pipeline-scan
        uses: veracode/Veracode-pipeline-scan-action@v1.0.10
        with:
          vid: ${{ secrets.VERACODE_API_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY }}
          veracode_policy_name: ${{ inputs.policy_name }}
          file: ./veracode_artifact_directory/${{ env.veracode_artifact }}
          fail_build: true

      # configure Veracode Static Analysis Pipeline Scan and SARIF import
      # from https://github.com/marketplace/actions/veracode-static-analysis-pipeline-scan-and-sarif-import
      - name: Veracode Static Analysis Pipeline Scan and SARIF import
        uses: veracode/veracode-pipeline-scan-results-to-sarif@v1.0.9

      - name: Veracode Static Scan
        uses: veracode/veracode-uploadandscan-action@0.2.6
        with:
          vid: ${{ secrets.VERACODE_API_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY }}
          filepath: ./veracode_artifact_directory/${{ env.veracode_artifact }}
